AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Video conversion workflow: Lambda function and MediaConvert transcoding service
Resources:
  myVODLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 120
      Role: 'arn:aws:iam::082266425766:role/MediaConvertLambdaRole'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
      Environment:
        Variables:
          Application: VOD
          MediaConvertRole: 'arn:aws:iam::082266425766:role/MediaConvert_Default_Role'
  Bucket1:
    Type: 'AWS::S3::Bucket'
